In [1]:
import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/cindzzi/Project-3/master/Clean%20data/CLEAN_NBA_TABLE_16-17.csv')
data.head(5)

,TEAM,GP,W,L,WIN%,MIN,PTS,FGM,FGA,FG%,...,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,+/-,RANK
0,Golden State Warriors,82,67,15,0.817,48.2,115.9,43.1,87.1,49.5,...,44.4,30.4,14.8,9.6,6.8,3.8,19.3,19.4,11.6,1
1,San Antonio Spurs,82,61,21,0.744,48.3,105.3,39.3,83.7,46.9,...,43.9,23.8,13.4,8.0,5.9,4.1,18.3,19.8,7.2,2
2,Houston Rockets,82,55,27,0.671,48.2,115.3,40.3,87.2,46.2,...,44.4,25.2,15.1,8.2,4.3,5.0,19.9,20.4,5.8,3
3,Boston Celtics,82,53,29,0.646,48.2,108.0,38.6,85.1,45.4,...,42.0,25.2,13.3,7.5,4.1,5.2,20.6,20.3,2.6,4
4,Cleveland Cavaliers,82,51,31,0.622,48.5,110.3,39.9,84.9,47.0,...,43.7,22.7,13.7,6.6,4.0,4.3,18.1,20.6,3.2,5

In [2]:
import sys
sys.path.append('/Users/adeliamanuel/anaconda3/envs/keras/lib/python3.7/site-packages')
import xgboost as xgb
from sklearn.model_selection import train_test_split

x = data[['TEAM', 'GP', 'W', 'L', 'PTS', '3P%']]
y = data['RANK']

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=1)

classifier = xgb.sklearn.XGBClassifier(nthread=-1, seed=1)
classifier.fit(X_train, y_train)

ValueError: DataFrame.dtypes for data must be int, float or bool.
                Did not expect the data types in fields TEAM