In [55]:
import warnings

warnings.simplefilter('ignore')

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [56]:
# Run the CSV
nba_stats = pd.read_excel('../Clean data/top_8_teams_2017-2018.xlsx')
nba_stats

,Unnamed: 0,Team,Game,Date,Home,Opponent,WINorLOSS,TeamPoints,OpponentPoints,FieldGoals,...,Opp.FreeThrows,Opp.FreeThrowsAttempted,Opp.FreeThrows.,Opp.OffRebounds,Opp.TotalRebounds,Opp.Assists,Opp.Steals,Opp.Blocks,Opp.Turnovers,Opp.TotalFouls
0,1,BOS,14,2017-11-12,Home,TOR,W,95,94,35,...,20,23,0.870,6,36,18,8.0,8.0,17.0,20.0
1,2,BOS,55,2018-02-06,Away,TOR,L,91,111,33,...,14,17,0.824,5,40,29,10.0,4.0,15.0,18.0
2,3,BOS,3,2017-10-20,Away,PHI,W,102,92,35,...,12,16,0.750,14,47,20,7.0,4.0,16.0,30.0
3,4,BOS,23,2017-11-30,Home,PHI,W,108,97,40,...,11,18,0.611,15,45,24,11.0,1.0,19.0,22.0
4,5,BOS,1,2017-10-17,Away,CLE,L,99,102,36,...,21,25,0.840,9,50,19,3.0,4.0,17.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,236,WAS,66,2018-03-09,Away,NOP,W,116,97,46,...,15,18,0.833,2,38,23,3.0,10.0,15.0,18.0
236,237,WAS,71,2018-03-21,Away,SAS,L,90,98,35,...,13,18,0.722,12,42,21,7.0,10.0,15.0,17.0
237,238,WAS,74,2018-03-27,Home,SAS,W,116,106,46,...,18,33,0.545,10,37,29,7.0,5.0,8.0,17.0
238,239,WAS,20,2017-11-28,Away,MIN,W,92,89,36,...,9,14,0.643,13,49,27,3.0,1.0,10.0,17.0
239,240,WAS,68,2018-03-13,Home,MIN,L,111,116,42,...,17,19,0.895,11,37,23,10.0,7.0,10.0,21.0

In [57]:
nba_stats.drop(nba_stats.columns[nba_stats.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
nba_stats

,Team,Game,Date,Home,Opponent,WINorLOSS,TeamPoints,OpponentPoints,FieldGoals,FieldGoalsAttempted,...,Opp.FreeThrows,Opp.FreeThrowsAttempted,Opp.FreeThrows.,Opp.OffRebounds,Opp.TotalRebounds,Opp.Assists,Opp.Steals,Opp.Blocks,Opp.Turnovers,Opp.TotalFouls
0,BOS,14,2017-11-12,Home,TOR,W,95,94,35,87,...,20,23,0.870,6,36,18,8.0,8.0,17.0,20.0
1,BOS,55,2018-02-06,Away,TOR,L,91,111,33,83,...,14,17,0.824,5,40,29,10.0,4.0,15.0,18.0
2,BOS,3,2017-10-20,Away,PHI,W,102,92,35,84,...,12,16,0.750,14,47,20,7.0,4.0,16.0,30.0
3,BOS,23,2017-11-30,Home,PHI,W,108,97,40,79,...,11,18,0.611,15,45,24,11.0,1.0,19.0,22.0
4,BOS,1,2017-10-17,Away,CLE,L,99,102,36,88,...,21,25,0.840,9,50,19,3.0,4.0,17.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,WAS,66,2018-03-09,Away,NOP,W,116,97,46,96,...,15,18,0.833,2,38,23,3.0,10.0,15.0,18.0
236,WAS,71,2018-03-21,Away,SAS,L,90,98,35,83,...,13,18,0.722,12,42,21,7.0,10.0,15.0,17.0
237,WAS,74,2018-03-27,Home,SAS,W,116,106,46,85,...,18,33,0.545,10,37,29,7.0,5.0,8.0,17.0
238,WAS,20,2017-11-28,Away,MIN,W,92,89,36,83,...,9,14,0.643,13,49,27,3.0,1.0,10.0,17.0
239,WAS,68,2018-03-13,Home,MIN,L,111,116,42,82,...,17,19,0.895,11,37,23,10.0,7.0,10.0,21.0

In [58]:
df = nba_stats[(nba_stats['Team'] == 'UTA') | (nba_stats['Opponent'] == 'SAS')]
TOR = df.iloc[:]
TOR.head(1)

,Team,Game,Date,Home,Opponent,WINorLOSS,TeamPoints,OpponentPoints,FieldGoals,FieldGoalsAttempted,...,Opp.FreeThrows,Opp.FreeThrowsAttempted,Opp.FreeThrows.,Opp.OffRebounds,Opp.TotalRebounds,Opp.Assists,Opp.Steals,Opp.Blocks,Opp.Turnovers,Opp.TotalFouls
26,BOS,7,2017-10-30,Home,SAS,W,108,94,42,88,...,10,20,0.5,12,40,24,8.0,4.0,11.0,14.0

In [59]:
nba_stats.WINorLOSS[nba_stats.WINorLOSS == 'W'] = 0
nba_stats.WINorLOSS[nba_stats.WINorLOSS == 'L'] = 1
nba_stats

,Team,Game,Date,Home,Opponent,WINorLOSS,TeamPoints,OpponentPoints,FieldGoals,FieldGoalsAttempted,...,Opp.FreeThrows,Opp.FreeThrowsAttempted,Opp.FreeThrows.,Opp.OffRebounds,Opp.TotalRebounds,Opp.Assists,Opp.Steals,Opp.Blocks,Opp.Turnovers,Opp.TotalFouls
0,BOS,14,2017-11-12,Home,TOR,0,95,94,35,87,...,20,23,0.870,6,36,18,8.0,8.0,17.0,20.0
1,BOS,55,2018-02-06,Away,TOR,1,91,111,33,83,...,14,17,0.824,5,40,29,10.0,4.0,15.0,18.0
2,BOS,3,2017-10-20,Away,PHI,0,102,92,35,84,...,12,16,0.750,14,47,20,7.0,4.0,16.0,30.0
3,BOS,23,2017-11-30,Home,PHI,0,108,97,40,79,...,11,18,0.611,15,45,24,11.0,1.0,19.0,22.0
4,BOS,1,2017-10-17,Away,CLE,1,99,102,36,88,...,21,25,0.840,9,50,19,3.0,4.0,17.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,WAS,66,2018-03-09,Away,NOP,0,116,97,46,96,...,15,18,0.833,2,38,23,3.0,10.0,15.0,18.0
236,WAS,71,2018-03-21,Away,SAS,1,90,98,35,83,...,13,18,0.722,12,42,21,7.0,10.0,15.0,17.0
237,WAS,74,2018-03-27,Home,SAS,0,116,106,46,85,...,18,33,0.545,10,37,29,7.0,5.0,8.0,17.0
238,WAS,20,2017-11-28,Away,MIN,0,92,89,36,83,...,9,14,0.643,13,49,27,3.0,1.0,10.0,17.0
239,WAS,68,2018-03-13,Home,MIN,1,111,116,42,82,...,17,19,0.895,11,37,23,10.0,7.0,10.0,21.0

In [60]:
nba_stats.Home[nba_stats.Home == 'Home'] = 0
nba_stats.Home[nba_stats.Home == 'Away'] = 1
nba_stats

,Team,Game,Date,Home,Opponent,WINorLOSS,TeamPoints,OpponentPoints,FieldGoals,FieldGoalsAttempted,...,Opp.FreeThrows,Opp.FreeThrowsAttempted,Opp.FreeThrows.,Opp.OffRebounds,Opp.TotalRebounds,Opp.Assists,Opp.Steals,Opp.Blocks,Opp.Turnovers,Opp.TotalFouls
0,BOS,14,2017-11-12,0,TOR,0,95,94,35,87,...,20,23,0.870,6,36,18,8.0,8.0,17.0,20.0
1,BOS,55,2018-02-06,1,TOR,1,91,111,33,83,...,14,17,0.824,5,40,29,10.0,4.0,15.0,18.0
2,BOS,3,2017-10-20,1,PHI,0,102,92,35,84,...,12,16,0.750,14,47,20,7.0,4.0,16.0,30.0
3,BOS,23,2017-11-30,0,PHI,0,108,97,40,79,...,11,18,0.611,15,45,24,11.0,1.0,19.0,22.0
4,BOS,1,2017-10-17,1,CLE,1,99,102,36,88,...,21,25,0.840,9,50,19,3.0,4.0,17.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,WAS,66,2018-03-09,1,NOP,0,116,97,46,96,...,15,18,0.833,2,38,23,3.0,10.0,15.0,18.0
236,WAS,71,2018-03-21,1,SAS,1,90,98,35,83,...,13,18,0.722,12,42,21,7.0,10.0,15.0,17.0
237,WAS,74,2018-03-27,0,SAS,0,116,106,46,85,...,18,33,0.545,10,37,29,7.0,5.0,8.0,17.0
238,WAS,20,2017-11-28,1,MIN,0,92,89,36,83,...,9,14,0.643,13,49,27,3.0,1.0,10.0,17.0
239,WAS,68,2018-03-13,0,MIN,1,111,116,42,82,...,17,19,0.895,11,37,23,10.0,7.0,10.0,21.0

In [61]:
uniqueTeams = nba_stats['Team'].unique()
dictTeams = {}
cnt = 1
for team in uniqueTeams:
    dictTeams[team] = cnt
    cnt+=1

dictTeams

for key,value in dictTeams.items():
    print('{} = {}'.format(key,value))
    #nba_stats['Team']== key and replace Team with value
    #nba_stats['Opponent'] == key and replace Opponent with value

BOS = 1
CLE = 2
GSW = 3
HOU = 4
IND = 5
MIA = 6
MIL = 7
MIN = 8
NOP = 9
OKC = 10
PHI = 11
POR = 12
SAS = 13
TOR = 14
WAS = 15

In [62]:
dictTeams['UTA'] = 16
dictTeams

{'BOS': 1,
 'CLE': 2,
 'GSW': 3,
 'HOU': 4,
 'IND': 5,
 'MIA': 6,
 'MIL': 7,
 'MIN': 8,
 'NOP': 9,
 'OKC': 10,
 'PHI': 11,
 'POR': 12,
 'SAS': 13,
 'TOR': 14,
 'WAS': 15,
 'UTA': 16}

In [63]:
nba_stats.replace(dictTeams, inplace=True)
nba_stats

,Team,Game,Date,Home,Opponent,WINorLOSS,TeamPoints,OpponentPoints,FieldGoals,FieldGoalsAttempted,...,Opp.FreeThrows,Opp.FreeThrowsAttempted,Opp.FreeThrows.,Opp.OffRebounds,Opp.TotalRebounds,Opp.Assists,Opp.Steals,Opp.Blocks,Opp.Turnovers,Opp.TotalFouls
0,1,14,2017-11-12,0,14,0,95,94,35,87,...,20,23,0.870,6,36,18,8.0,8.0,17.0,20.0
1,1,55,2018-02-06,1,14,1,91,111,33,83,...,14,17,0.824,5,40,29,10.0,4.0,15.0,18.0
2,1,3,2017-10-20,1,11,0,102,92,35,84,...,12,16,0.750,14,47,20,7.0,4.0,16.0,30.0
3,1,23,2017-11-30,0,11,0,108,97,40,79,...,11,18,0.611,15,45,24,11.0,1.0,19.0,22.0
4,1,1,2017-10-17,1,2,1,99,102,36,88,...,21,25,0.840,9,50,19,3.0,4.0,17.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,15,66,2018-03-09,1,9,0,116,97,46,96,...,15,18,0.833,2,38,23,3.0,10.0,15.0,18.0
236,15,71,2018-03-21,1,13,1,90,98,35,83,...,13,18,0.722,12,42,21,7.0,10.0,15.0,17.0
237,15,74,2018-03-27,0,13,0,116,106,46,85,...,18,33,0.545,10,37,29,7.0,5.0,8.0,17.0
238,15,20,2017-11-28,1,8,0,92,89,36,83,...,9,14,0.643,13,49,27,3.0,1.0,10.0,17.0
239,15,68,2018-03-13,0,8,1,111,116,42,82,...,17,19,0.895,11,37,23,10.0,7.0,10.0,21.0

In [64]:
nba_stats.drop(nba_stats.columns[nba_stats.columns.str.contains('Date',case = False)],axis = 1, inplace = True)
nba_stats

,Team,Game,Home,Opponent,WINorLOSS,TeamPoints,OpponentPoints,FieldGoals,FieldGoalsAttempted,FieldGoals.,...,Opp.FreeThrows,Opp.FreeThrowsAttempted,Opp.FreeThrows.,Opp.OffRebounds,Opp.TotalRebounds,Opp.Assists,Opp.Steals,Opp.Blocks,Opp.Turnovers,Opp.TotalFouls
0,1,14,0,14,0,95,94,35,87,0.402,...,20,23,0.870,6,36,18,8.0,8.0,17.0,20.0
1,1,55,1,14,1,91,111,33,83,0.398,...,14,17,0.824,5,40,29,10.0,4.0,15.0,18.0
2,1,3,1,11,0,102,92,35,84,0.417,...,12,16,0.750,14,47,20,7.0,4.0,16.0,30.0
3,1,23,0,11,0,108,97,40,79,0.506,...,11,18,0.611,15,45,24,11.0,1.0,19.0,22.0
4,1,1,1,2,1,99,102,36,88,0.409,...,21,25,0.840,9,50,19,3.0,4.0,17.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,15,66,1,9,0,116,97,46,96,0.479,...,15,18,0.833,2,38,23,3.0,10.0,15.0,18.0
236,15,71,1,13,1,90,98,35,83,0.422,...,13,18,0.722,12,42,21,7.0,10.0,15.0,17.0
237,15,74,0,13,0,116,106,46,85,0.541,...,18,33,0.545,10,37,29,7.0,5.0,8.0,17.0
238,15,20,1,8,0,92,89,36,83,0.434,...,9,14,0.643,13,49,27,3.0,1.0,10.0,17.0
239,15,68,0,8,1,111,116,42,82,0.512,...,17,19,0.895,11,37,23,10.0,7.0,10.0,21.0

In [65]:
nba_stats = nba_stats.dropna(how='any')
nba_stats

,Team,Game,Home,Opponent,WINorLOSS,TeamPoints,OpponentPoints,FieldGoals,FieldGoalsAttempted,FieldGoals.,...,Opp.FreeThrows,Opp.FreeThrowsAttempted,Opp.FreeThrows.,Opp.OffRebounds,Opp.TotalRebounds,Opp.Assists,Opp.Steals,Opp.Blocks,Opp.Turnovers,Opp.TotalFouls
0,1,14,0,14,0,95,94,35,87,0.402,...,20,23,0.870,6,36,18,8.0,8.0,17.0,20.0
1,1,55,1,14,1,91,111,33,83,0.398,...,14,17,0.824,5,40,29,10.0,4.0,15.0,18.0
2,1,3,1,11,0,102,92,35,84,0.417,...,12,16,0.750,14,47,20,7.0,4.0,16.0,30.0
3,1,23,0,11,0,108,97,40,79,0.506,...,11,18,0.611,15,45,24,11.0,1.0,19.0,22.0
4,1,1,1,2,1,99,102,36,88,0.409,...,21,25,0.840,9,50,19,3.0,4.0,17.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,15,66,1,9,0,116,97,46,96,0.479,...,15,18,0.833,2,38,23,3.0,10.0,15.0,18.0
236,15,71,1,13,1,90,98,35,83,0.422,...,13,18,0.722,12,42,21,7.0,10.0,15.0,17.0
237,15,74,0,13,0,116,106,46,85,0.541,...,18,33,0.545,10,37,29,7.0,5.0,8.0,17.0
238,15,20,1,8,0,92,89,36,83,0.434,...,9,14,0.643,13,49,27,3.0,1.0,10.0,17.0
239,15,68,0,8,1,111,116,42,82,0.512,...,17,19,0.895,11,37,23,10.0,7.0,10.0,21.0

In [66]:
nba_stats.drop(nba_stats.columns[nba_stats.columns.str.contains('TeamPoints', case = False)],axis = 1, inplace = True)
nba_stats

,Team,Game,Home,Opponent,WINorLOSS,OpponentPoints,FieldGoals,FieldGoalsAttempted,FieldGoals.,X3PointShots,...,Opp.FreeThrows,Opp.FreeThrowsAttempted,Opp.FreeThrows.,Opp.OffRebounds,Opp.TotalRebounds,Opp.Assists,Opp.Steals,Opp.Blocks,Opp.Turnovers,Opp.TotalFouls
0,1,14,0,14,0,94,35,87,0.402,10,...,20,23,0.870,6,36,18,8.0,8.0,17.0,20.0
1,1,55,1,14,1,111,33,83,0.398,10,...,14,17,0.824,5,40,29,10.0,4.0,15.0,18.0
2,1,3,1,11,0,92,35,84,0.417,10,...,12,16,0.750,14,47,20,7.0,4.0,16.0,30.0
3,1,23,0,11,0,97,40,79,0.506,12,...,11,18,0.611,15,45,24,11.0,1.0,19.0,22.0
4,1,1,1,2,1,102,36,88,0.409,8,...,21,25,0.840,9,50,19,3.0,4.0,17.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,15,66,1,9,0,97,46,96,0.479,9,...,15,18,0.833,2,38,23,3.0,10.0,15.0,18.0
236,15,71,1,13,1,98,35,83,0.422,8,...,13,18,0.722,12,42,21,7.0,10.0,15.0,17.0
237,15,74,0,13,0,106,46,85,0.541,10,...,18,33,0.545,10,37,29,7.0,5.0,8.0,17.0
238,15,20,1,8,0,89,36,83,0.434,10,...,9,14,0.643,13,49,27,3.0,1.0,10.0,17.0
239,15,68,0,8,1,116,42,82,0.512,8,...,17,19,0.895,11,37,23,10.0,7.0,10.0,21.0

In [67]:
nba_stats.drop(nba_stats.columns[nba_stats.columns.str.contains('OpponentPoints',case = False)],axis = 1, inplace = True)
nba_stats

,Team,Game,Home,Opponent,WINorLOSS,FieldGoals,FieldGoalsAttempted,FieldGoals.,X3PointShots,X3PointShotsAttempted,...,Opp.FreeThrows,Opp.FreeThrowsAttempted,Opp.FreeThrows.,Opp.OffRebounds,Opp.TotalRebounds,Opp.Assists,Opp.Steals,Opp.Blocks,Opp.Turnovers,Opp.TotalFouls
0,1,14,0,14,0,35,87,0.402,10,26,...,20,23,0.870,6,36,18,8.0,8.0,17.0,20.0
1,1,55,1,14,1,33,83,0.398,10,23,...,14,17,0.824,5,40,29,10.0,4.0,15.0,18.0
2,1,3,1,11,0,35,84,0.417,10,29,...,12,16,0.750,14,47,20,7.0,4.0,16.0,30.0
3,1,23,0,11,0,40,79,0.506,12,29,...,11,18,0.611,15,45,24,11.0,1.0,19.0,22.0
4,1,1,1,2,1,36,88,0.409,8,32,...,21,25,0.840,9,50,19,3.0,4.0,17.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,15,66,1,9,0,46,96,0.479,9,26,...,15,18,0.833,2,38,23,3.0,10.0,15.0,18.0
236,15,71,1,13,1,35,83,0.422,8,25,...,13,18,0.722,12,42,21,7.0,10.0,15.0,17.0
237,15,74,0,13,0,46,85,0.541,10,24,...,18,33,0.545,10,37,29,7.0,5.0,8.0,17.0
238,15,20,1,8,0,36,83,0.434,10,28,...,9,14,0.643,13,49,27,3.0,1.0,10.0,17.0
239,15,68,0,8,1,42,82,0.512,8,20,...,17,19,0.895,11,37,23,10.0,7.0,10.0,21.0

In [68]:
X = nba_stats.drop("WINorLOSS", axis=1)
y = nba_stats["WINorLOSS"]
print(X.shape, y.shape)

(239, 36) (239,)

In [69]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test, = train_test_split(X, y, random_state=1, stratify=y)

In [70]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [71]:
nba_stats.dtypes

Team                          int64
Game                          int64
Home                          int64
Opponent                      int64
WINorLOSS                     int64
FieldGoals                    int64
FieldGoalsAttempted           int64
FieldGoals.                 float64
X3PointShots                  int64
X3PointShotsAttempted         int64
X3PointShots.               float64
FreeThrows                    int64
FreeThrowsAttempted           int64
FreeThrows.                 float64
OffRebounds                   int64
TotalRebounds                 int64
Assists                       int64
Steals                        int64
Blocks                        int64
Turnovers                     int64
TotalFouls                    int64
Opp.FieldGoals                int64
Opp.FieldGoalsAttempted       int64
Opp.FieldGoals.             float64
Opp.3PointShots               int64
Opp.3PointShotsAttempted      int64
Opp.3PointShots.            float64
Opp.FreeThrows                int64
Opp.FreeThrowsAttempted       int64
Opp.FreeThrows.             float64
Opp.OffRebounds               int64
Opp.TotalRebounds             int64
Opp.Assists                   int64
Opp.Steals                  float64
Opp.Blocks                  float64
Opp.Turnovers               float64
Opp.TotalFouls              float64
dtype: object

In [72]:
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [73]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.9666666666666667

In [74]:
predictions = classifier.predict(X_test)
table = pd.DataFrame({"Prediction": predictions, "Actual": y_test})
table['Correct'] = table.Prediction == table.Actual
table

     Prediction  Actual  Correct
165           0       0     True
175           1       1     True
136           1       1     True
120           1       1     True
23            0       0     True
50            0       0     True
206           1       1     True
208           0       0     True
19            0       0     True
214           1       1     True
27            1       1     True
176           1       1     True
28            0       0     True
2             0       0     True
182           1       1     True
141           1       1     True
145           0       0     True
40            0       0     True
134           1       1     True
191           1       1     True
16            0       0     True
56            1       1     True
112           1       1     True
166           0       0     True
128           1       1     True
144           0       0     True
51            1       1     True
8             0       0     True
135           0       0     True
11            0       0     True
33            0       0     True
152           0       0     True
79            1       1     True
153           0       0     True
35            1       1     True
200           0       1    False
227           1       1     True
22            1       1     True
85            0       0     True
114           0       0     True
204           1       1     True
55            1       1     True
207           0       0     True
31            0       0     True
9             1       1     True
150           1       1     True
162           0       0     True
142           1       1     True
212           0       0     True
196           0       0     True
233           0       1    False
21            0       0     True
20            0       0     True
183           0       0     True
157           0       0     True
203           1       1     True
34            1       1     True
225           1       1     True
49            0       0     True
69            0       0     True

In [75]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        31
           1       1.00      0.93      0.96        29

    accuracy                           0.97        60
   macro avg       0.97      0.97      0.97        60
weighted avg       0.97      0.97      0.97        60

In [76]:
import pickle

with open('nbamodel.pkl', 'wb') as file:
    pickle.dump(classifier, file)

In [77]:
classifier = pickle.load(open('nbamodel.pkl', 'rb'))